version: "3.3"
services:
  app:
    build:
      args:
        user: sherlock
        uid: 2000
      context: ./
      dockerfile: Dockerfile
    image: localhost:8000/skeleton
    container_name: skeleton-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - skeleton

  db:
    image: mysql:5.7
    container_name: skeleton
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - skeleton

  nginx:
    image: nginx:alpine
    container_name: skeleton-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - skeleton

networks:
  skeleton:
    driver: bridge